on:
  workflow_dispatch:
    push:

name: "Projeto

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform

      - name: "Terraform Init"
        run: terraform init
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY}}

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY}}

