name: Provision t3.micro EC2
on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: 'App Server'
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: aws-actions/configure-aws-credentials@v4
        name: Configure AWS credentials
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY}}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_KEY}}'
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v2
        name: Setup Terraform
        with:
          terraform_wrapper: false

      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
